print-status: False

api:
    database:
        dialect: ${DATABASE_DIALECT:sqlite}
        settings:
            check_same_thread: False
    server:
        port: 6088

swagger:
    schemes: [https]
    host: ${SWAGGER_HOST:localhost}
