print-status: False

api:
    database:
        dialect: ${DATABASE_DIALECT:sqlite}
        settings:
            check_same_thread: False

swagger:
    schemes: [${api.server.scheme}] ###- bug
    host: ${SWAGGER_HOST:${api.server.host}}:${api.server.port} ###- bug
